# services : is a list of containers
services:
  # MongoDB Container Name
  mymongodb:
    # since mongo is an offical image we can use it.
    image: "mongo"

    # MongoDB server port
    ports:
      - "27017:27017"

    # Mongodb depends on volume to keep the data alive.
    volumes:
      - data:/data/db

    # Environment variables
    environment:
      MONGO_INITDB_ROOT_USERNAME: "rezwan"
      MONGO_INITDB_ROOT_PASSWORD: "12345"

  # Server
  backend:
    # Build an image based on Dockerfile in /server
    build: ./server
    # Backend Port
    ports:
      - "5000:5000"

    # Depends on MongoDB to run
    depends_on:
      - mymongodb

  # Client
  frontend:
    # Build an image based on Dockerfile in /client
    build: ./client

    # Client port
    ports:
      - "3000:3000"
    # add bind mount volume to keep have updated source code
    volumes:
      - ./client/src:/app/src
    # allow interactive mode
    stdin_open: true
    tty: true

    # Client depends on server, which depends on backend
    depends_on:
      - backend

# declare the volumes name that our app is using.
volumes:
  data: